name: Docker file scan for frontend
on: 
    workflow_call:
jobs: 
    Docker_file_scan_for_frontend:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v6

            - name: dockerfile scanning
              uses: hadolint/hadolint-action@v3.1.0
              with: 
                dockerfile: ./frontend/Dockerfile
                failure-threshold: warning 