name: Final DevSecOps pipeline
on:
  workflow_dispatch:
jobs:
  secret_leak_check:
    uses: ./.github/workflows/Git-leaks-check.yml
    secrets: inherit
    

  packages_check:
    uses: ./.github/workflows/OWASP-dependency-check.yml
    secrets: inherit
    needs: ["secret_leak_check"]

  docker_file_scan_frontend:
    uses: ./.github/workflows/DockerFile-lint-frontend.yml
    secrets: inherit
    needs: ["packages_check"]

  docker_file_scan_backend:
    uses: ./.github/workflows/DockerFile-lint-backend.yml
    secrets: inherit
    needs: ["docker_file_scan_frontend"]

  trivy_image_scan:
    needs:
      [
        "docker_file_scan_backend"
      ]
    uses: ./.github/workflows/Trivy-scan.yml
    secrets: inherit

  Gitops-CI:
    needs: ["trivy_image_scan"]
    uses: ./.github/workflows/CI.yml
    secrets: inherit
